### ISSUE TITLE
Add a new property to the text-input-options

### ISSUE THREAD

**Issue by lealea401** [Vuepic/vue-datepicker#473]
I am testing the VueDatePicker with the text-input option turned on.
The bug detected in the issue https://github.com/Vuepic/vue-datepicker/issues/455 was solved! Thanks !!!

Using the same configuration:
`<VueDatePicker :model-value="selectedDate" @update:model-value="handleDateUpdate" :clearable="false" :year-range="[1900,2470]" auto-apply text-input :text-input-options="textInputOptions" ></VueDatePicker>`

I noticed that now I can type in a date but to save it I need to press "enter" on the keyboard.
This is because the allowed text-input-options properties are:
`{ enterSubmit: true, tabSubmit: true, openMenu: true, rangeSeparator: '-' }`

If I type in the date and then click outside the calendar (auto-apply on), the calendar closes but the date is not saved and returns to the original input.

**Solution I'd like**
Would it be possible to add a new property to the text-input-options such that if I use "auto-apply", after I type in the date, I click outside the calendar, the calendar closes and the date is saved in the input box?

**Comment by lealea401** [comment]
Dear Jasenkoo when do you plan to deliver the new release 6.0.0 ? Thanks a lot!

**Comment by dathacky** [comment]
+1

**Comment by Jasenkoo** [comment]
@lealea401 @dathacky What version are you using? This should already happen if the `auto-apply` is set to true. The only reason it might revert to the previous one is if the typed date is invalid.

**Comment by dathacky** [comment]
> 

Yes, the user clears the input to null, I would expect that when the user blurs out of the input, the date in the input box will update itself to a valid date. @Jasenkoo

**Comment by Jasenkoo** [comment]
The fix is included in the released v6

**Comment by Jasenkoo** [comment]
@dathacky Here is the working [example](https://stackblitz.com/edit/vuepic-vue-datepicker-xfm3qy?file=src%2Fcomponents%2FPlayground.vue). Everything works as expected

**Comment by dathacky** [comment]
thank you, its work for me

**Comment by lealea401** [comment]
@Jasenkoo , I am trying your example (https://stackblitz.com/edit/vuepic-vue-datepicker-xfm3qy?file=src%2Fcomponents%2FPlayground.vue)...I am sorry I cannot add also a video to it to show you how I try it. I still see issues in you example. 
1) I pick up a date from the calendar (08/24/2023, 17:15)
2) I am modifying by hand the date (09/24/2023, 17:15) and click outside the input box
3) The date reverts to 08/24/2023, 17:15

The date changes only if I use the calendar. I cannot make it work if I am modifyinig the date manually.
Is there something that I am doing wrong?

@dathacky says it works for him. What am I doing wrong? I am using Chrome and Firefox on windows 10.

**Comment by lealea401** [comment]
@Jasenkoo @alessandromontesanti thank you for your suggestions.

I am using Gitlab CI/Cd to build my application. 
In babel.config.js I added the plugin
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset' 
  ],
  "plugins": [
    '@babel/plugin-transform-nullish-coalescing-operator' 
                                                                                           
  ]
}
but I get this error:
ERROR  Error: Cannot find module '@babel/plugin-transform-nullish-coalescing-operator'

Could you guide me? Thanks!!

**Comment by Jasenkoo** [comment]
@lealea401 Did you run `npm install` or `yarn install`, maybe you are using a lock file to pull dependencies in the CI action, which will ignore the package.json listed dependency if the lock file is not updated.

**Comment by lealea401** [comment]
@Jasenkoo, I removed package-lock.json and run again but the error persists. I ran your playground locally using vite and it worked but when I used "vue-cli-service" it failed. I am wondering if I can open a ticket to request to have version 6.0.0 working with vue-cli-service instead of vite. Version 5.4.0 works with vue-cli-service and I don't understand why 6.0.0 doesn't work the same way.

**Comment by Jasenkoo** [comment]
@lealea401 What is your node version? I'll try to replicate it locally

**Comment by lealea401** [comment]
@Jasenkoo I use node 15.2.
Do I need to update these dependencies (they worked well with VueDatepicker 5.4.0) ?
"devDependencies": {
"@vue/cli-plugin-babel": "^4.5.13",
"@vue/cli-plugin-eslint": "^4.5.13",
"@vue/cli-plugin-pwa": "^4.5.13",
"@vue/cli-plugin-router": "^4.5.13",
"@vue/cli-plugin-vuex": "^4.5.13",
"@vue/cli-service": "^4.5.13",
"@vue/compiler-sfc": "^3.2.19",
"babel-eslint": "^10.1.0",
"eslint": "^6.7.2",
"eslint-plugin-vue": "^7.18.0",
"node-sass": "^4.12.0",
"sass-loader": "^8.0.2"
}

**Comment by lealea401** [comment]
@Jasenkoo,
After a lot of tests, it turned out that indeed, I needed to updated the dependencies:
<img width="927" alt="1" src="https://github.com/Vuepic/vue-datepicker/assets/51837829/61ab29b2-68cb-4268-b862-ae0d112b2a1f">
The migration of vue-cli from 4.5 to 5 solved the problem related to VueDatePicker but introduced an issue related to the absolute path in the url used in the scss file...the same issue as described here: 
https://github.com/vuejs/vue-cli/issues/7032

As suggested in this link I had to modify vue.config.js by adding:
```
  css: {
    loaderOptions: {
      css: {
        url: false,
      }
    }
  },

```
In the end I had the VueDatepicker 6.0.1 working:

https://github.com/Vuepic/vue-datepicker/assets/51837829/3a67bf2f-15c5-4cc4-b48b-a87afb7acd6b

I only hope that there will be no other side effects in my project due to the vue-cli/babel/eslint migration...

Could you tell me if the vue-cli/eslint/babel migration makes sense to you given the latest changes that were done to the datepicker  ?

**Comment by Jasenkoo** [comment]
@lealea401 You should be good, I would maybe first try with node 16 LTS, but updating vue-cli is also a good idea

**Comment by lealea401** [comment]
@Jasenkoo Thank you for your support

**Comment by lealea401** [comment]
@Jasenkoo thank you for your support.
Just one last question...With version 5.4.0 I was using
`<VueDatePicker v-model="dateTo" :alt-position="() => ({ top: 170, left: 80 })" :teleport="true" :format="dateFormat" :min-date="dateFrom" :max-date="dateToMax()" :year-range="[dateFromToYear(),dateToMaxToYear()]" :enable-time-picker="false" :clearable="false" auto-apply  @blur="dateFromBlur" />`

where
```
        dateFromBlur(value) {
            const d = new Date(value);
            const min = new Date('1950-01-01');
            if (d < min) {
                this.dateFrom = UtilsService.dateToStringTechnical(min);
            }
        },

```
If I add text-input at the end, the date doe not change it I try to modify it manually. Maybe it comes into conflict with @blue event?

`<VueDatePicker v-model="dateTo" :alt-position="() => ({ top: 170, left: 80 })" :teleport="true" :format="dateFormat" :min-date="dateFrom" :max-date="dateToMax()" :year-range="[dateFromToYear(),dateToMaxToYear()]" :enable-time-picker="false" :clearable="false" auto-apply  @blur="dateToBlur" text-input />`

**Comment by lealea401** [comment]
`@Jasenkoo` thank you for your support.
Just one last question...With version 5.4.0 I was using
`<VueDatePicker v-model="dateTo" :alt-position="() => ({ top: 170, left: 80 })" :teleport="true" :format="dateFormat" :min-date="dateFrom" :max-date="dateToMax()" :year-range="[dateFromToYear(),dateToMaxToYear()]" :enable-time-picker="false" :clearable="false" auto-apply  @blur="dateFromBlur" />`

where
```
dateFormat(date) {
            const day = String(date.getDate()).padStart(2, '0');
            const month = String(date.getMonth() + 1).padStart(2, '0');
            const year = date.getFullYear();
             return `${day}/${month}/${year}`;
        },

```
If I add text-input at the end, the date does not change it I try to modify it manually. 
`<VueDatePicker v-model="dateTo" :alt-position="() => ({ top: 170, left: 80 })" :teleport="true" :format="dateFormat" :min-date="dateFrom" :max-date="dateToMax()" :year-range="[dateFromToYear(),dateToMaxToYear()]" :enable-time-picker="false" :clearable="false" auto-apply  @blur="dateToBlur" text-input />`

I noticed that the issue is with   ":format="dateFormat". If I use format="dd/MM/yyyy" it works. Why cannot I use a specific formatting anymore as in version 5.4.0?

**Comment by christian-benseler-farm** [comment]
I managed to fix whis is my project (using Vue 3 + webpack 4) with babel-loader. In vue.config.js,

`configureWebpack: {
	module: {
		rules: [
			{
				test: /\.js$/,
				loader: 'babel-loader',
				include: /node_modules\/@vuepic/,
			},
		],
	},
}`

**Comment by nermin99** [comment]
Hi @lealea401, what combination of dependencies and respective versions are you using today? I am also using vue cli plugin
