### ISSUE TITLE
`#action-row` slot type throws error after update

### ISSUE THREAD

**Issue by felixgabler** [Vuepic/vue-datepicker#1185]
**Describe the bug**
After updating to v12 and renaming `internalModelValue` to `modelValue` in `#action-row` (according to the migration guide), we now get:

```
app/components/generic/forms/basic/DatePicker.vue:46:59 - error TS2339: Property 'modelValue' does not exist on type 'ActionRowSlotProps'.

46         <template #action-row="{ closePicker, selectDate, modelValue, disabled }">
                                                             ~~~~~~~~~~
```

I have confirmed that the behavior is correct though. It writes it as `modelValue` and not `internalModelValue`. It is just the type check that fails.

**To Reproduce**
1. Install version `^12.0.3`
2. Run `vue-tsc`

**Expected behavior**
The type checker should not complain

**Desktop & mobile (please complete the following information):**
 - Library version: `12.0.3`
